// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: pictures/pictures.proto

package analytics

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Picture message
type PictureMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title  string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Base64 string `protobuf:"bytes,3,opt,name=base64,proto3" json:"base64,omitempty"`
	UserId string `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *PictureMessage) Reset() {
	*x = PictureMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pictures_pictures_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PictureMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PictureMessage) ProtoMessage() {}

func (x *PictureMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pictures_pictures_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PictureMessage.ProtoReflect.Descriptor instead.
func (*PictureMessage) Descriptor() ([]byte, []int) {
	return file_pictures_pictures_proto_rawDescGZIP(), []int{0}
}

func (x *PictureMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PictureMessage) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PictureMessage) GetBase64() string {
	if x != nil {
		return x.Base64
	}
	return ""
}

func (x *PictureMessage) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// Pictures message
type PicturesMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pictures []*PictureMessage `protobuf:"bytes,1,rep,name=pictures,proto3" json:"pictures,omitempty"`
}

func (x *PicturesMessage) Reset() {
	*x = PicturesMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pictures_pictures_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PicturesMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PicturesMessage) ProtoMessage() {}

func (x *PicturesMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pictures_pictures_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PicturesMessage.ProtoReflect.Descriptor instead.
func (*PicturesMessage) Descriptor() ([]byte, []int) {
	return file_pictures_pictures_proto_rawDescGZIP(), []int{1}
}

func (x *PicturesMessage) GetPictures() []*PictureMessage {
	if x != nil {
		return x.Pictures
	}
	return nil
}

// GetUserPictures request
type GetUserPicturesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *GetUserPicturesRequest) Reset() {
	*x = GetUserPicturesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pictures_pictures_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserPicturesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPicturesRequest) ProtoMessage() {}

func (x *GetUserPicturesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pictures_pictures_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPicturesRequest.ProtoReflect.Descriptor instead.
func (*GetUserPicturesRequest) Descriptor() ([]byte, []int) {
	return file_pictures_pictures_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserPicturesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// GetUserPicture request
type GetUserPictureRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId    string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PictureId string `protobuf:"bytes,2,opt,name=picture_id,json=pictureId,proto3" json:"picture_id,omitempty"`
}

func (x *GetUserPictureRequest) Reset() {
	*x = GetUserPictureRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pictures_pictures_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserPictureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPictureRequest) ProtoMessage() {}

func (x *GetUserPictureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pictures_pictures_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPictureRequest.ProtoReflect.Descriptor instead.
func (*GetUserPictureRequest) Descriptor() ([]byte, []int) {
	return file_pictures_pictures_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserPictureRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserPictureRequest) GetPictureId() string {
	if x != nil {
		return x.PictureId
	}
	return ""
}

// CreateUserPicture request
type CreateUserPictureRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title  string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Base64 string `protobuf:"bytes,2,opt,name=base64,proto3" json:"base64,omitempty"`
	UserId string `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *CreateUserPictureRequest) Reset() {
	*x = CreateUserPictureRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pictures_pictures_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateUserPictureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserPictureRequest) ProtoMessage() {}

func (x *CreateUserPictureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pictures_pictures_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserPictureRequest.ProtoReflect.Descriptor instead.
func (*CreateUserPictureRequest) Descriptor() ([]byte, []int) {
	return file_pictures_pictures_proto_rawDescGZIP(), []int{4}
}

func (x *CreateUserPictureRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateUserPictureRequest) GetBase64() string {
	if x != nil {
		return x.Base64
	}
	return ""
}

func (x *CreateUserPictureRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// DeleteUserPicture request
type DeleteUserPictureRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId    string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PictureId string `protobuf:"bytes,2,opt,name=picture_id,json=pictureId,proto3" json:"picture_id,omitempty"`
}

func (x *DeleteUserPictureRequest) Reset() {
	*x = DeleteUserPictureRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pictures_pictures_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteUserPictureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserPictureRequest) ProtoMessage() {}

func (x *DeleteUserPictureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pictures_pictures_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserPictureRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserPictureRequest) Descriptor() ([]byte, []int) {
	return file_pictures_pictures_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteUserPictureRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeleteUserPictureRequest) GetPictureId() string {
	if x != nil {
		return x.PictureId
	}
	return ""
}

var File_pictures_pictures_proto protoreflect.FileDescriptor

var file_pictures_pictures_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x73, 0x2f, 0x70, 0x69, 0x63, 0x74, 0x75,
	0x72, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6d, 0x61, 0x69, 0x6e, 0x1a,
	0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x67, 0x0a, 0x0e,
	0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74,
	0x69, 0x74, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x61, 0x73, 0x65, 0x36, 0x34, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x61, 0x73, 0x65, 0x36, 0x34, 0x12, 0x17, 0x0a, 0x07,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x43, 0x0a, 0x0f, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65,
	0x73, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x30, 0x0a, 0x08, 0x70, 0x69, 0x63, 0x74,
	0x75, 0x72, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6d, 0x61, 0x69,
	0x6e, 0x2e, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x52, 0x08, 0x70, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x73, 0x22, 0x31, 0x0a, 0x16, 0x47, 0x65,
	0x74, 0x55, 0x73, 0x65, 0x72, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x4f, 0x0a,
	0x15, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x1d, 0x0a, 0x0a, 0x70, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x49, 0x64, 0x22, 0x61,
	0x0a, 0x18, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x50, 0x69, 0x63, 0x74,
	0x75, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69,
	0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x62, 0x61, 0x73, 0x65, 0x36, 0x34, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x62, 0x61, 0x73, 0x65, 0x36, 0x34, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x22, 0x52, 0x0a, 0x18, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x50,
	0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a,
	0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x69, 0x63, 0x74, 0x75, 0x72,
	0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x69, 0x63, 0x74,
	0x75, 0x72, 0x65, 0x49, 0x64, 0x32, 0xb7, 0x02, 0x0a, 0x08, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72,
	0x65, 0x73, 0x12, 0x48, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x50, 0x69, 0x63,
	0x74, 0x75, 0x72, 0x65, 0x73, 0x12, 0x1c, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x47, 0x65, 0x74,
	0x55, 0x73, 0x65, 0x72, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x50, 0x69, 0x63, 0x74, 0x75,
	0x72, 0x65, 0x73, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x00, 0x12, 0x45, 0x0a, 0x0e,
	0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x12, 0x1b,
	0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x50, 0x69, 0x63,
	0x74, 0x75, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x6d, 0x61,
	0x69, 0x6e, 0x2e, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x22, 0x00, 0x12, 0x4b, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65,
	0x72, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x12, 0x1e, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e,
	0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x00,
	0x12, 0x4d, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x50, 0x69,
	0x63, 0x74, 0x75, 0x72, 0x65, 0x12, 0x1e, 0x2e, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x50, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x42,
	0x35, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x6f,
	0x72, 0x7a, 0x68, 0x61, 0x6e, 0x6f, 0x76, 0x2f, 0x67, 0x6f, 0x2d, 0x72, 0x65, 0x61, 0x6c, 0x77,
	0x6f, 0x72, 0x6c, 0x64, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x61, 0x6e, 0x61,
	0x6c, 0x79, 0x74, 0x69, 0x63, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pictures_pictures_proto_rawDescOnce sync.Once
	file_pictures_pictures_proto_rawDescData = file_pictures_pictures_proto_rawDesc
)

func file_pictures_pictures_proto_rawDescGZIP() []byte {
	file_pictures_pictures_proto_rawDescOnce.Do(func() {
		file_pictures_pictures_proto_rawDescData = protoimpl.X.CompressGZIP(file_pictures_pictures_proto_rawDescData)
	})
	return file_pictures_pictures_proto_rawDescData
}

var file_pictures_pictures_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pictures_pictures_proto_goTypes = []interface{}{
	(*PictureMessage)(nil),           // 0: main.PictureMessage
	(*PicturesMessage)(nil),          // 1: main.PicturesMessage
	(*GetUserPicturesRequest)(nil),   // 2: main.GetUserPicturesRequest
	(*GetUserPictureRequest)(nil),    // 3: main.GetUserPictureRequest
	(*CreateUserPictureRequest)(nil), // 4: main.CreateUserPictureRequest
	(*DeleteUserPictureRequest)(nil), // 5: main.DeleteUserPictureRequest
	(*emptypb.Empty)(nil),            // 6: google.protobuf.Empty
}
var file_pictures_pictures_proto_depIdxs = []int32{
	0, // 0: main.PicturesMessage.pictures:type_name -> main.PictureMessage
	2, // 1: main.Pictures.GetUserPictures:input_type -> main.GetUserPicturesRequest
	3, // 2: main.Pictures.GetUserPicture:input_type -> main.GetUserPictureRequest
	4, // 3: main.Pictures.CreateUserPicture:input_type -> main.CreateUserPictureRequest
	5, // 4: main.Pictures.DeleteUserPicture:input_type -> main.DeleteUserPictureRequest
	1, // 5: main.Pictures.GetUserPictures:output_type -> main.PicturesMessage
	0, // 6: main.Pictures.GetUserPicture:output_type -> main.PictureMessage
	0, // 7: main.Pictures.CreateUserPicture:output_type -> main.PictureMessage
	6, // 8: main.Pictures.DeleteUserPicture:output_type -> google.protobuf.Empty
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pictures_pictures_proto_init() }
func file_pictures_pictures_proto_init() {
	if File_pictures_pictures_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pictures_pictures_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PictureMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pictures_pictures_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PicturesMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pictures_pictures_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserPicturesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pictures_pictures_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserPictureRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pictures_pictures_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateUserPictureRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pictures_pictures_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteUserPictureRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pictures_pictures_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pictures_pictures_proto_goTypes,
		DependencyIndexes: file_pictures_pictures_proto_depIdxs,
		MessageInfos:      file_pictures_pictures_proto_msgTypes,
	}.Build()
	File_pictures_pictures_proto = out.File
	file_pictures_pictures_proto_rawDesc = nil
	file_pictures_pictures_proto_goTypes = nil
	file_pictures_pictures_proto_depIdxs = nil
}
