version: "2"
services:
  analytics:
    build: ./analytics
    container_name: gorealworld_analytics_service
    ports:
      - "3001:3081"
      - "5001:5081"
    depends_on:
      - jaeger
      - psql
      - elasticsearch
      - kibana
      - prometheus
      - grafana
      - kafka
    networks:
      - go-realworld

  auth:
    build: ./auth
    container_name: gorealworld_auth_service
    ports:
      - "3002:3082"
      - "5002:5082"
    depends_on:
      - jaeger
      - psql
      - elasticsearch
      - kibana
      - prometheus
      - grafana
      - kafka
    networks:
      - go-realworld

  pictures:
    build: ./pictures
    container_name: gorealworld_pictures_service
    ports:
      - "3003:3083"
      - "5003:5083"
    depends_on:
      - jaeger
      - psql
      - elasticsearch
      - kibana
      - prometheus
      - grafana
      - kafka
    networks:
      - go-realworld

  users:
    build: ./users
    container_name: gorealworld_users_service
    ports:
      - "3004:3084"
      - "5004:5084"
    depends_on:
      - jaeger
      - psql
      - elasticsearch
      - kibana
      - prometheus
      - grafana
      - kafka
    networks:
      - go-realworld

  apigw:
    build: ./apigw
    container_name: gorealworld_apigw_service
    ports:
      - "3005:3085"
    depends_on:
      - analytics
      - auth
      - pictures
      - users
    networks:
      - go-realworld

  web:
    build: ./web
    container_name: gorealworld_web_service
    ports:
      - "8000:8000"
    depends_on:
      - apigw
    networks:
      - go-realworld

  postgres:
    extends:
      file: "./docker-compose.deps.yml"
      service: postgres
  jaeger:
    extends:
      file: "./docker-compose.deps.yml"
      service: jaeger
  elasticsearch:
    extends:
      file: "./docker-compose.deps.yml"
      service: elasticsearch
  kibana:
    extends:
      file: "./docker-compose.deps.yml"
      service: kibana
  filebeat:
    extends:
      file: "./docker-compose.deps.yml"
      service: filebeat
  prometheus:
    extends:
      file: "./docker-compose.deps.yml"
      service: prometheus
  grafana:
    extends:
      file: "./docker-compose.deps.yml"
      service: grafana
  zookeeper:
    extends:
      file: "./docker-compose.deps.yml"
      service: zookeeper
  kafka:
    extends:
      file: "./docker-compose.deps.yml"
      service: kafka

networks:
  go-realworld:
