analytics:
  rest:
    logData:
      method: POST
      url: /analytics
    getLogs:
      method: GET
      url: /analytics/:offset
  events:
    logData:
      event: logData
    getLogs:
      event: getLogs

auth:
  rest:
    validateEventsRequest:
      method: GET
      url: auth
    login:
      method: POST
      url: login
    signup:
      method: POST
      url: signup
  events:
    validateEventsRequest:
      event: validateEventsRequest
    login:
      event: login
    signup:
      event: signup

pictures:
  rest:
    getPictures:
      method: GET
      url: /pictures/:userId
    getPicture:
      method: GET
      url: /pictures/:userId/:id
    createPicture:
      method: POST
      url: /pictures
    deletePicture:
      method: DELETE
      url: /pictures/:userId/:id
  events:
    getPictures:
      event: getPictures
    getPicture:
      event: getPicture
    createPicture:
      event: createPicture
    deletePicture:
      event: deletePicture

users:
  rest:
    getUser:
      method: GET
      url: /users/:id
    getUserByUsername:
      method: GET
      url: /users
    validatePassword:
      method: POST
      url: /users/validate-password
    createUser:
      method: POST
      url: /users
    deleteUser:
      method: DELETE
      url: /users/:id
  events:
    getUser:
      event: getUser
    getUserByUsername:
      event: getUserByUsername
    validatePassword:
      event: validatePassword
    createUser:
      event: createUser
    deleteUser:
      event: deleteUser
